# Generated by Django 2.0.2 on 2019-06-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_vehiculo',
            name='marca_Vehiculo',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo_Vehiculo',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Modelo_Vehiculo',
        ),
    ]
