# Generated by Django 2.0.2 on 2019-06-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculoapp', '0002_auto_20190622_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Estado_Vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca_Vehiculo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_Combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Tipo_Combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_Transmicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Transmicion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_Vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Tipo_Vehiculo'),
        ),
        migrations.DeleteModel(
            name='Marca_Vehiculo',
        ),
    ]
