# Generated by Django 2.0.2 on 2019-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculoapp', '0002_auto_20190621_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_vehiculo',
            name='marca_Vehiculo',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca_Vehiculo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo_Vehiculo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_Combustible',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_Transmicion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_Vehiculo',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Estado_Vehiculo',
        ),
        migrations.DeleteModel(
            name='Marca_Vehiculo',
        ),
        migrations.DeleteModel(
            name='Modelo_Vehiculo',
        ),
        migrations.DeleteModel(
            name='Tipo_Combustible',
        ),
        migrations.DeleteModel(
            name='Tipo_Vehiculo',
        ),
        migrations.DeleteModel(
            name='Transmicion',
        ),
    ]
