# Generated by Django 2.0.2 on 2019-06-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculoapp', '0003_auto_20190622_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_vehiculo',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Estado_Vehiculo'),
        ),
    ]
