# Generated by Django 2.0.2 on 2019-06-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculoapp', '0003_auto_20190622_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_vehiculo',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
