# Generated by Django 2.0.2 on 2019-06-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clienteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fechanacimiento']},
        ),
    ]
