# Generated by Django 2.0.2 on 2019-06-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_Vehiculo', models.CharField(max_length=20)),
                ('numero_puertas', models.IntegerField()),
                ('capacidad_personas', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=7)),
                ('funciones', models.TextField()),
                ('capacidad_maletero', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('modelo_Vehiculo', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('apellido_cliente', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('dui', models.CharField(max_length=9, unique=True)),
                ('fecha_alquiler', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_Combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Tipo_Combustible')),
                ('tipo_Transmicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Transmicion')),
                ('tipo_Vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculoapp.Tipo_Vehiculo')),
            ],
        ),
    ]
