# Generated by Django 2.0.2 on 2019-06-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
