# Generated by Django 2.0.2 on 2019-06-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecliente', models.CharField(max_length=30)),
                ('apellidocliente', models.CharField(max_length=30)),
                ('fechanacimiento', models.DateTimeField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('identificador', models.CharField(max_length=200)),
            ],
        ),
    ]
