# Generated by Django 2.0.2 on 2019-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=10, unique=True)),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('apellido_cliente', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('dui', models.CharField(max_length=9, unique=True)),
                ('password', models.TextField(max_length=15)),
            ],
        ),
    ]
