# Generated by Django 2.0.2 on 2019-06-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clienteapp', '0003_cliente_ididentificador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-ididentificador']},
        ),
    ]
