# Generated by Django 2.0.2 on 2019-06-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteapp', '0004_auto_20190621_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechanacimiento',
            field=models.DateField(),
        ),
    ]
